### ISSUE TITLE
StopIteration error on default installation

### ISSUE THREAD

**Issue by riramar** [Nefcore/CRLFsuite#5]
I've installed CRLFsuite under Kali latest version with all updates.

```
$ git clone https://github.com/Nefcore/CRLFsuite.git
$ cd CRLFsuite
$ sudo python3 setup.py install
```

When I tried to run for the very first time got the error below.
```
$ crlfsuite -h
Traceback (most recent call last):
  File "/usr/local/bin/crlfsuite", line 33, in <module>
    sys.exit(load_entry_point('CRLFsuite==2.1.1', 'console_scripts', 'crlfsuite')())
  File "/usr/local/bin/crlfsuite", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
```

**Comment by Raghavd3v** [comment]
Hi @riramar,

Thanks for reporting, Currently we're in the process of confirming the issue then we'll move to the fixing process, If the issue exists then it will be fixed in the next update.

**Comment by Raghavd3v** [comment]
We believe the issue you reported is invalid because we tried installing and running CRLFsuite on multiple platforms like Kali Linux's latest version (2022.2) and on Android using termux. Still, we didn't get the error you reported so we are closing this issue.

You're probably getting this error because of the following reasons:

* Some issue's with setuptools module
* Outdated Kali Linux
* Outdated Python
* Outdated CRLFsuite

**Comment by riramar** [comment]
Thanks! I'm sure my Kali is up-to-dated but is not working.
I'll try to find another tool.

![image](https://user-images.githubusercontent.com/6748242/181569428-5fa76f40-0159-4522-8154-32a554be1dbc.png)

**Comment by Raghavd3v** [comment]
Yeah sure, you can try another tool 👍 ,  crlfuzz is also a good tool for CRLF injection scanning but we have a solution for this issue:

The `StopIteration` occurs when `importlib_load_entry_point ` fails to find the relevant package.  The issue only occurs when using setup.py install because that's the code path that uses easy_install with this script launcher technique so this issue can be fixed using `sudo pip install crlfsuite` and don't forget to uninstall the previous crlfsuite - `sudo pip uninstall crlfsuite`
